// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIpEqFKnPKBMZvWiTDjvyulNlju_4MWt4',
    appId: '1:644675052484:web:89671e56a7f0eec3597a91',
    messagingSenderId: '644675052484',
    projectId: 'example-dc304',
    authDomain: 'example-dc304.firebaseapp.com',
    storageBucket: 'example-dc304.appspot.com',
    measurementId: 'G-BF6TEJE2X0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPLbYcwGY6TXz_DKp1dchT0sI4IF8dGT4',
    appId: '1:644675052484:android:4b44ff7ac8dcc893597a91',
    messagingSenderId: '644675052484',
    projectId: 'example-dc304',
    storageBucket: 'example-dc304.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ-xKWO6_kICAb7wkXhv61dajAOxyY7YE',
    appId: '1:644675052484:ios:c4e7c6b3a29f5e30597a91',
    messagingSenderId: '644675052484',
    projectId: 'example-dc304',
    storageBucket: 'example-dc304.appspot.com',
    iosClientId: '644675052484-0meocqt82o818h8hdkmhkgf4fbu4jivk.apps.googleusercontent.com',
    iosBundleId: 'com.bmc.firebaseExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ-xKWO6_kICAb7wkXhv61dajAOxyY7YE',
    appId: '1:644675052484:ios:c4e7c6b3a29f5e30597a91',
    messagingSenderId: '644675052484',
    projectId: 'example-dc304',
    storageBucket: 'example-dc304.appspot.com',
    iosClientId: '644675052484-0meocqt82o818h8hdkmhkgf4fbu4jivk.apps.googleusercontent.com',
    iosBundleId: 'com.bmc.firebaseExample',
  );
}
